"""
The generated parts of the admin API contract, taken from the code rather than written by
hand: the endpoint table in docs/ADMIN_API_CONTRACT.md (every admin API call the BFF
makes, what it sends, the answer it expects, and which roles can cause it) and
docs/admin-api.schema.json (the JSON Schema of every answer). They come from making every
request of test_routes.ROUTES as an owner, against the stand-in, and recording what goes
out.

    python -m bff.tests.contract_doc           rewrite both
    python -m bff.tests.contract_doc --check   exit 1 if either is out of date (test_contract_doc runs this)
"""

from __future__ import annotations

import json
import re
import sys
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Optional

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from bff.app import contract as C
from bff.app.admin_client import AdminClient
from bff.app.members import CAPABILITIES, ROLES
from bff.app.routes import _forward, audit, config, me

from .conftest import Harness, dev_settings
from .test_routes import ROUTES

ROOT = Path(__file__).resolve().parents[2]
DOC = ROOT / "docs" / "ADMIN_API_CONTRACT.md"
SCHEMA = ROOT / "docs" / "admin-api.schema.json"
START = "<!-- generated by python -m bff.tests.contract_doc: do not edit by hand -->"
END = "<!-- end of the generated table -->"
PRUNING = (_forward, audit, config, me)
# Calls whose answer the BFF checks without contract.prune (events.py cleans each event).
ANSWERS = {("GET", "/admin/v1/events"): C.EventList}
STREAM = ("GET", "/admin/v1/events/stream", ["after"], "GET /bff/events/stream", "tickets.events")


class Call:
    def __init__(self, method: str, path: str, query: Any, body: Any, bff: str, capability: str):
        self.method, self.path = method, _template(path)
        self.query = sorted(query or {})
        self.body = sorted(body or {}) if isinstance(body, dict) else []
        self.bff, self.capability = bff, capability
        self.model: Optional[type[BaseModel]] = ANSWERS.get((method, self.path))


def _template(path: str) -> str:
    path = re.sub(r"/\d+(?=/|$)", "/{id}", path)
    return re.sub(r"^(/admin/v1/(?:plans))/(?!\{)[^/]+", r"\1/{plan_id}", path)


@contextmanager
def recording(where: dict[str, str]) -> Iterator[list[Call]]:
    calls: list[Call] = []
    original_call = AdminClient.call
    original_prune = _forward.prune

    async def call(self: AdminClient, method: str, path: str, **kw: Any) -> Any:
        calls.append(Call(method, path, kw.get("query"), kw.get("body"), where["bff"], where["capability"]))
        return await original_call(self, method, path, **kw)

    def prune(data: Any, model: type[BaseModel], label: str = "") -> Any:
        for recorded in reversed(calls):
            if recorded.model is None:
                recorded.model = model
                break
        return original_prune(data, model, label)

    AdminClient.call = call  # type: ignore[method-assign]
    for module in PRUNING:
        module.prune = prune  # type: ignore[attr-defined]
    try:
        yield calls
    finally:
        AdminClient.call = original_call  # type: ignore[method-assign]
        for module in PRUNING:
            module.prune = original_prune  # type: ignore[attr-defined]


def _bff_template(openapi: dict[str, Any], method: str, path: str) -> str:
    """The route template ("/bff/users/{user_id}") that a concrete path belongs to."""
    for template, operations in openapi["paths"].items():
        pattern = re.sub(r"\\\{[^}]+\\\}", "[^/]+", re.escape(template))
        if method.lower() in operations and re.fullmatch(pattern, path):
            return template
    raise LookupError(f"no BFF route for {method} {path}")


def collect() -> list[dict[str, Any]]:
    h = Harness(dev_settings("owner"))
    openapi = h.app.openapi()
    where = {"bff": "", "capability": ""}
    try:
        with recording(where) as calls:
            for method, path, body, capability in [*ROUTES, ("GET", "/bff/health", None, "")]:
                where["bff"] = f"{method} {_bff_template(openapi, method, path.split('?')[0])}"
                where["capability"] = capability
                r = h.get(path) if method == "GET" else h.send(method, path, body)
                assert r.status_code == 200, (method, path, r.status_code)
    finally:
        h.client.close()

    rows: dict[tuple[str, str], dict[str, Any]] = {}
    extra = Call(STREAM[0], STREAM[1], dict.fromkeys(STREAM[2]), None, STREAM[3], STREAM[4])
    for c in [*calls, extra]:
        row = rows.setdefault(
            (c.path, c.method),
            {"method": c.method, "path": c.path, "sends": set(), "model": None, "bff": [], "roles": set()},
        )
        row["sends"].update(c.query)
        row["sends"].update(_body_fields(openapi, c.bff) if c.method != "GET" else c.body)
        row["model"] = row["model"] or c.model
        if c.bff not in row["bff"]:
            row["bff"].append(c.bff)
        row["roles"].update(CAPABILITIES[c.capability] if c.capability else ROLES)
    return [rows[key] for key in sorted(rows)]


def _body_fields(openapi: dict[str, Any], bff: str) -> list[str]:
    method, path = bff.split(" ", 1)
    operation = openapi["paths"][path][method.lower()]
    ref = operation.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema", {})
    name = ref.get("$ref", "").rsplit("/", 1)[-1]
    return sorted(openapi["components"]["schemas"].get(name, {}).get("properties", {})) if name else []


def _roles(roles: set[str]) -> str:
    return "every role" if roles == set(ROLES) else ", ".join(r for r in ROLES if r in roles)


def table(rows: list[dict[str, Any]]) -> str:
    lines = [
        "| Admin API call | The BFF sends | Answer (`contract.py`) | Roles that can cause it | For |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        model = row["model"]
        answer = f"`{model.__name__}`" if model else "server-sent events of `OutboxEvent`"
        sends = ", ".join(f"`{s}`" for s in sorted(row["sends"])) or "nothing"
        bff = "<br>".join(f"`{b}`" for b in row["bff"])
        lines.append(f"| `{row['method']} {row['path']}` | {sends} | {answer} | {_roles(row['roles'])} | {bff} |")
    return "\n".join(lines) + "\n"


def schema(rows: list[dict[str, Any]]) -> str:
    models = sorted({row["model"] for row in rows if row["model"]} | {C.OutboxEvent}, key=lambda m: m.__name__)
    _, top = models_json_schema([(m, "serialization") for m in models], title="AnotherNote admin API answers")
    top["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    top["description"] = (
        "What the admin app accepts from each admin API endpoint (docs/ADMIN_API_CONTRACT.md). Generated from "
        "bff/app/contract.py; every object forbids fields it does not name."
    )
    return json.dumps(top, indent=2, sort_keys=True) + "\n"


def render() -> tuple[str, str]:
    rows = collect()
    doc = DOC.read_text(encoding="utf-8")
    head, rest = doc.split(START, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{START}\n{table(rows)}{END}{tail}", schema(rows)


def main(argv: list[str]) -> int:
    doc, schema_text = render()
    current = (DOC.read_text(encoding="utf-8"), SCHEMA.read_text(encoding="utf-8") if SCHEMA.exists() else "")
    if "--check" in argv:
        if (doc, schema_text) != current:
            print(
                "docs/ADMIN_API_CONTRACT.md or docs/admin-api.schema.json is out of date: python -m bff.tests.contract_doc"
            )
            return 1
        return 0
    DOC.write_text(doc, encoding="utf-8")
    SCHEMA.write_text(schema_text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
